site_name: Harlon Government Portal
theme:
  name: material
  logo: logo.png
  favicon: logo.png
  font:
    text: Manrope
  palette:
    - media: "(prefers-color-scheme: light)" # 

      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: green
    - media: "(prefers-color-scheme: dark)" # 

      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: green
  features:
    - navigation.tabs
features:
    - navigation.instant
    - navigation.sections
    - navigation.indexes
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences


